### ISSUE TITLE
Certificate Service Authentication Failure

### ISSUE THREAD

**Issue by Silvenga** [bodsch/docker-icinga2#21]
### Subject of the issue
Certificate Service does not use `ICINGA_CERT_SERVICE_BA_USER` or `ICINGA_CERT_SERVICE_BA_PASSWORD` to setup basic authorization. Rather the service uses the hardcored values of `admin:admin`. This leads to confusion around the usage of the above mentioned environment variables.

### Steps to reproduce

Master:
```
ICINGA_CERT_SERVICE_BA_USER = user
ICINGA_CERT_SERVICE_BA_PASSWORD = password
```

Satellite:
```
ICINGA_CERT_SERVICE_BA_USER = user
ICINGA_CERT_SERVICE_BA_PASSWORD = password
``` 

### Expected behaviour
When the satellite is requesting a new certificate from the Certificate Service, the request should succeed. 

### Actual behaviour
401 error when attempting to get a certificate due to basic authentication challenge failure.

**Comment by bodsch** [comment]
which branch has you used?
